### ISSUE TITLE
Supervisor does not restart app on provision

### ISSUE THREAD

**Issue by timini** [repositive/ansible-ember-lightning#1]
I had reprovisioned the frontend but the app had not been restarted.

Should this be part of a provision task or is it more the responsibility of a deploy task?

**Comment by timini** [comment]
@zemanel shall I close this?

**Comment by zemanel** [comment]
@timini can you still reproduce ? if not, close.

**Comment by timini** [comment]
fixed in https://github.com/repositive/ansible-ember-lightning/commit/ccf2d90f9ac172c82dd927def011c141a3b44b11
